### ISSUE TITLE
Spawnrate Gegner (Level 1)

### ISSUE THREAD

**Issue by leonmuelhens** [lhrb/swec8#41]
Spawnrate muss angepasst werden (Mehr Gegner sollen am Anfang spawnen, weniger steigerung der Spawnrate zum Ende hin)

**Comment by leonmuelhens** [comment]
atan((0.8*x)-3)+1.9 --> 0.5*(atan((0.5*x)-3)+3.6)

wie gut ist das gebalanced?

**Comment by lhrb** [comment]
Die Spawnrate müsste für alle Level überarbeitet werden! 
So als idee einfach eine lineare Funktion? (wahrscheinlich der geringste Aufwand)
