### ISSUE TITLE
Background Image/Buttonstyle Levelauswahl

### ISSUE THREAD

**Issue by Thorsten1** [lhrb/swec8#55]
![levelselect](https://user-images.githubusercontent.com/793376/50547615-4adc4a00-0c3d-11e9-88a4-ca6f7f9d9baa.PNG)
Wie Man auf dem Bild sieht muss das Bild noch angepasst werden, da die Knöpfe viel kleiner sind

**Comment by lhrb** [comment]
oder die Knöpfe :D

**Comment by Thorsten1** [comment]
@lhrb  ginge auch aber och würde sagen dann sind die zu groß, da die Knöpfe ja auch imm Hauptmenü zum Beispiel nicht so groß sind

**Comment by lhrb** [comment]
Ne mach das mal nicht, da das eh noch nicht richtig ist.
Laut lastenheft müssen wir da einen code eingeben können ....

**Comment by cwaninger** [comment]
Hast Recht. Das ist aktuell nur so, damit man die Level überhaupt testen kann einzeln. Es fehlt der Code wie du schon sagst.
Abgesehen davon sollte das Bild nicht die Buttons beinhalten. Heißt wir sollten den Background so anpassen dass keine Buttons vorgegeben sind. So kann man die Table beliebig anpassen und muss nicht so viel hantieren. Außerdem kann man somit einfach weitere Level hinzufügen oder rausnehmen etc.

**Comment by JanKlemens** [comment]
![unbenannt](https://user-images.githubusercontent.com/44291027/50766107-57355800-1278-11e9-9ff0-f20edd019a94.PNG)
Hab grade da mal ein bisschen rumprobiert (und aufpoliert) und ohne die buttonrahmen sieht das eigentlich auch ganz gut aus
