### ISSUE TITLE
Gametime bleibt beim "weiter spielen" (Leveltransition)

### ISSUE THREAD

**Issue by cwaninger** [lhrb/swec8#57]
Wenn man das LEvel durchspielt und dann weiter spielen klickt, muss die gameTime resettet werden oder?

**Comment by Thorsten1** [comment]
Habe ich mich auch schon gefragt. Bin mir aber unsicher weil definiert ist es glaube ich nicht irgendwo.

**Comment by lhrb** [comment]
Macht ja schon Sinn, dass die bleibt wenn man das Spiel in einem durchspielt.

**Comment by Thorsten1** [comment]
Ich würde das issue jetzt auch einfach mal schließen weil ich auch sagen würde, dass das so gut ist.
