### ISSUE TITLE
Eintragen von Highscore bleibt "Username" noch stehen.

### ISSUE THREAD

**Issue by cwaninger** [lhrb/swec8#59]
Beim reinklicken in das Textfeld für die Usereingabe, sollte der Text "Username" verschwinden.

**Comment by Thorsten1** [comment]
Guter Punkt versucht mich noch ein zu bauen am Samstag oder Sonntag. Bin bis Freitag Abend in München

**Comment by Thorsten1** [comment]
View Pull Reuest
https://github.com/lhrb/swec8/pull/64
