### ISSUE TITLE
Falsche Images werden benutzt, wenn assets neben der .jar datei liegen

### ISSUE THREAD

**Issue by cwaninger** [lhrb/swec8#6]
Scenario:
Ich habe player.png vor einiger Zeit runtergeladen und das Bild liegt in meinem Downloads Ordner. Es ist das Alte Bild vom Player (das große).
Dann habe ich die alpha-Jar-datei runtergeladen aus Slack und ingame ist der Spieler ultra groß (fast das ganze spielfeld).
Dann habe ich um sicherzustellen die png Datei renamed und das Problem war verschwunden.

Wir müssen darauf achten das nur die Assets die in der .jar-Datei inkludiert sind benutzt werden

**Comment by Thorsten1** [comment]
it's not a bug. It's a feature!

**Comment by lhrb** [comment]
Ich würde das jetzt auch mal als Feature ansehen (man kann seine eigenen Grafiken benutzten :D )
